import React from 'react'
import {EquipmentAbilities} from '../../../../../component'
function weaponAbility() {
  return (
    <div>
    <br />
      <>
        <h1 id="s-cinestesia" align="center" className='texto-resaltado-modifican'> Habilidades con armas cuerpo a cuerpo</h1>
        <img  className='character-images' src="https://res.cloudinary.com/dfrda73uc/image/upload/v1682607180/donGions%20imgs/habilidades%20con%20armas/fisico_lplrom.png" alt="Escudo" />
      </>
      <div className='texto-resaltado-degradado'>Todas las armas de dos manos se pueden sujetar con una, pero disminuye el acierto -1 por cada carga del arma y todos los golpes fallidos cuentan como contundentes</div>
      <EquipmentAbilities   equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682557090/donGions%20imgs/habilidades%20con%20armas/lanzamiento_brutal_m9mitk.jpg"} titleEquip={"Lanzamiento brutal"} textEquip={`: Prepara un arma para lanzarla. Cuanto más pesada sea, más daño hará. `} textEquip1={"Se tira dado de 4 por cada carga del arma y aumenta la probabilidad de que se rompa igual al resultado."} textEquip2={"Si el daño sale crítico, la criatura queda empalada, se le amputa una parte del cuerpo, se le destruye alguna parte de la armadura etc."} textEquip3={"Esta habilidad también se puede usar con objetos mundanos, pero los efectos dependen de las intenciones del personaje y el acierto total"}/>
      <EquipmentAbilities   equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682469244/donGions%20imgs/habilidades%20con%20armas/desarme_stxd5b.jpg"} titleEquip={"Desarme"} textEquip={": Sólo tras parar un ataque o de que te paren. Requiere superar a la otra criatura en lanzamiento de dados de 20 y tienes acierto incrementado igual al daño que has parado. Por ejemplo: si la parada te ha absorbido 60% de 10 puntos de daño, te aumenta tu acierto total en 6 puntos."}/>
      <EquipmentAbilities   equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682470352/donGions%20imgs/habilidades%20con%20armas/brut_okcbv0.jpg"} titleEquip={"Contundencia"} textEquip={": Preparas un ataque poderoso que dobla daño y acierto del arma, pero te costará sujetarlo tras impactar o fallar, así que no puedes usarlo en la siguiente ronda. Los látigos y cuerdas envuelven a la persona u objeto para tirar de ellas."}/>
      <EquipmentAbilities   equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682470060/donGions%20imgs/habilidades%20con%20armas/frontal_z0epvl.jpg"} titleEquip={"Barrido frontal"} textEquip={": Hace el daño en un cono. Si por ejemplo se hace el barrido de izquierda a derecha, la primera criatura en la trayectoria recibe todo el daño y el resto la mitad. Disminuye el acierto en 1 por cada criatura en la trayectoria. En acierto o daño alto, empujas a las criaturas hacia atrás."}/>
      <EquipmentAbilities   equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682469267/donGions%20imgs/habilidades%20con%20armas/barrido_circular_btd15o.jpg"} titleEquip={"Barrido circular"} textEquip={": Gasta dos acciones para completar el giro. Daño de barrido a todas las criaturas alrededor. Disminuye tu acierto 1 punto por criatura cercana y debes tirar por acierto por cada criatura. Si por ejemplo hay 4 criaturas, obtienes -4 en acierto y debes tirar 4 veces, una por cada criatura"}/>
      <EquipmentAbilities   equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682471598/donGions%20imgs/habilidades%20con%20armas/aguz_wtmji6.jpg"} titleEquip={"Aguzar el arma"} textEquip={": Aumenta el acierto del lanzamiento del arma +3 ese turno y disminuye la rotura en 5. Puedes gastar otra acción y maná para carga más el ataque, lo que te otorgaría +1 en precisión, otras -5 en rotura y un dado de 4 caras por cada carga del arma para el daño"}/>
    </div>
  )
}

export default weaponAbility