import React from 'react'
import {EquipmentAbilities} from '../../../..'


function weaponDistanceAbility() {
  return (
    <div>
    <br />
      <>
        <h1 id="s-cinestesia" align="center" className='texto-resaltado-modifican'> Habilidades con armas a distancia</h1> 
        <img  className='character-images' src="https://res.cloudinary.com/dfrda73uc/image/upload/v1682607179/donGions%20imgs/habilidades%20con%20armas/distancia_amyq2a.png" alt="Escudo" />
      </>
      <div className='texto-resaltado-degradado'>El arma especifica cuál de las habilidades se puede usar y se gastas 1 punto de maná para activarlo.</div>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556106/donGions%20imgs/habilidades%20con%20armas/reload_pk2aje.png"} titleEquip={"Recarga"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Obtienes 2 cargas de munición. La munición corresponde al tipo de arma que estás usando en el momento y no se puede intercambiar con otro jugador"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682632396/donGions%20imgs/habilidades%20con%20armas/apuntarr_nh0921.png"}  titleEquip={"Apuntar"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Aumenta el acierto a distancia +2 hasta el final del turno. Puedes gastar una acción adicional para obtener +1 en precisión a distancia para el disparo"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556579/donGions%20imgs/habilidades%20con%20armas/telescopio_ksoxlq.png"}  titleEquip={"Mira telescópica"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Aumenta el alcance a distancia +1. Puedes gastar una acción más para aumentar el alcande +1 adicional y la precisión a distancia para ese disparo en +1."}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682631788/donGions%20imgs/habilidades%20con%20armas/women-bow-arrows-archery-wallpaper-preview_wkucpi.png"}  titleEquip={"Tensar"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Aumenta el alcance a distancia +1 por nivel y el acierto obtiene un dado de 4 adicional. Puedes gastar una acción más para que tensar obtenga un dado de 4 adicional para acierto y daño."}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682631781/donGions%20imgs/habilidades%20con%20armas/gatillo_rapido_l07d76.png"}  titleEquip={"Gatillo rápido"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Aumenta la velocidad a distancia +1 para el siguiente disparo. Puedes gastar una acción más para aumentar la velocidad y precisión a distancia +1 adicionales para ese disparo"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556774/donGions%20imgs/habilidades%20con%20armas/fragmentacion_cuf2jw.png"}  titleEquip={"Bala de fragmentación"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": El siguiente disparo hace daño en cono 2x3 a todas las criaturas. Puedes gastar una acción adicional para añadir un dado de 4 en daño por cada criatura. Se tira por separado por cada criatura afectada."}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556106/donGions%20imgs/habilidades%20con%20armas/punta_solida_l8ji3z.jpg"}  titleEquip={"Bala de punta sólida"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": El siguiente disparo atraviesa a todas las criaturas en línea. Se tira por acierto a distancia por todas. Puedes gastar una acción más para aumentar el daño sobre la primera criatura en dado de 4 por cada nivel que tengas"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556087/donGions%20imgs/habilidades%20con%20armas/Explosiva_cecznr.png"}  titleEquip={"Bala explosiva"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Por cada punto de daño que tenga el arma, incluyendo gemas, enctantamientos etc, obtienes un dado de 4 para su siguiente disparo. Si el arma hace 3 puntos de daño, lanzas 3 dados de 4 caras si la bala impacta. Adicionalmente, si el resultado de los dados es superior a la mitad del daño, expulsas a la criatura en la dirección contraria"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556106/donGions%20imgs/habilidades%20con%20armas/esencias_f0fscq.png"}  titleEquip={"Bala de esencias"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": El siguiente disparo roba una esencia a la criatura a la que daña. La criatura debe estar viva.  Puedes gastar una acción más para que en su lugar robe esencias igual al resultado de un dado de 4"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556106/donGions%20imgs/habilidades%20con%20armas/magica_xlscdg.png"}  titleEquip={"Bala mágica"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": El siguiente disparo también hace daño mágico igual a tu daño de hechizos. Puedes gastar una acción adicional para quemar maná a la critura igual al daño hecho"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556574/donGions%20imgs/habilidades%20con%20armas/aturdimiento_hu0pbv.png"}  titleEquip={"Bala de aturdimiento"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Bala no letal que incapacita a la criatura tantos turnos como daño fuera a hacer. Si la criatura sufre daño o se interactua con él con violencia, saldrá del aturdimiento antes."}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556751/donGions%20imgs/habilidades%20con%20armas/carga_yzysgj.jpg"}  titleEquip={"Bala con carga"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Explota al impactar sobre el objetivo, haciendo el mismo daño sobre él y todas las criaturas cercanas. Puedes gastar una acción adicional para obtener un dado de 4 por cada criatura afectada y repartes el daño resultado equitativamente"}/>
      <EquipmentAbilities imageAbility={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682556105/donGions%20imgs/habilidades%20con%20armas/PEM_v761et.png"}  titleEquip={"Bala PEM"} equipCost={"https://res.cloudinary.com/dfrda73uc/image/upload/v1682456317/donGions%20imgs/costes/Captura_de_pantalla_2023-04-25_a_las_21.55.03_h7drgx.png"} textEquip={": Silencias a la criatura una ronda y le quita 3 puntos de maná +1 por nivel. Si la criatura es mecánica, queda desactivada tantos turnos como el resultado de un dado de 4."}/>
    </div>
  )
}

export default weaponDistanceAbility